### ISSUE TITLE
In flight risk includes unendorsed HTLCs

### ISSUE THREAD

**Issue by morehouse** [carlaKC/lrc#33]
If unendorsed HTLCs add to the in-flight risk, it is trivial to jam the victim.  Just send high-value HTLCs through the target channels and hodl them.  This creates a ridiculously high in-flight risk and effectively stops all endorsement propagation.

I assume this is an implementation error since https://github.com/lightning/bolts/pull/1071 states that in flight risk should be calculated from only endorsed HTLCs.

**Comment by carlaKC** [comment]
> I assume this is an implementation error since https://github.com/lightning/bolts/pull/1071 states that in flight risk should be calculated from only endorsed HTLCs.

Bug! Thanks for reporting.
